### ISSUE TITLE
make number of parallel jobs an argument

### ISSUE THREAD

**Issue by hahahannes** [ViCCo-Group/frrsa#23]

**Comment by PhilippKaniuth** [comment]
You actually mean the number of cores to use, right?

If so, you could change the type of the already existing argument `parallel` from Boolean to int.

Then, `parallel=1` would correspond to the current `parallel=False`. Anything else would correspond to the current `parallel=True`. Any integer would be a direct indication of how many cores to use (i.e. it would assign `number_cores`). 

A problem could be for people using this on servers, where you'd just want to use the maximum number of physical cores w/out knowing how many there actually are. This could be solved by either reserving one integer for indicating this (e.g. `parallel=999`) or by changing the type of the argument `parallel` to string and e.g. use "max" then.

This would be nicer because we wouldn't have another argument.

**Comment by hahahannes** [comment]
Totally aggree! Less parameters are better
